= Appendix 1 - Camel JBang
:experimental:
:tip-caption: :bulb:
:imagesdir: images

== 1. Camel JBang について

Camel JBangは、Apache Camelを使いやすくするためのツールです。Camel JBangを使用すると、シンプルなスクリプトファイルを使用してCamelルートを実行できます。

以下にCamel JBangの基本的なコマンドを示します。

[cols="2,7",options="header",role="custom-table"]
|===
| コマンド | 内容
| init | Camel の 基本的な Route を作成する
| run | 指定したCamelスクリプトファイルを実行
| version | インストールされているCamel JBangのバージョンを表示
| help | 使用可能なコマンドの一覧とその説明を表示
| export | CamelプロジェクトをMavenプロジェクトとしてエクスポート。
| transform route| CamelのDSLの形式変換（YAML ↔︎ XML）
| ps | ローカルで実行している Camel を監視する
| stop | ローカルで実行中の Camel を停止する
| debug | Camel Route のデバッグを行う
|===

その他のコマンドや詳細については、link:https://camel.apache.org/manual/camel-jbang.html[Camel JBang,window="_blank"] のドキュメントを確認してください。

== 2. Camel Route の作成と実行

`init` コマンドを使用して、新しい基本 Route を作成できます

例えば、YAML形式の Route を作成するには、以下のようにします。

[source, bash]
----
camel init sample.yaml
----

サンプルルートを含むファイルをsample.yaml（現在のディレクトリに）作成します。

ファイルを実行するには、次のコマンドを実行します。

[source, bash]
----
camel run sample.yaml
----

[TIP]
====
Camel では、YAML、XML、Javaなど、サポートされている link:https://camel.apache.org/manual/dsl.html[DSL,window="_blank"] を作成して実行できます。
====

== 3. Camel Quarkus, Camel Springboot へのエクスポート

`camel export --runtime=quarkus` コマンドは、現在のCamel JBangファイルを、Mavenベースの `Quarkus` プロジェクトにエクスポートします。

例えば、Maven の groupId `com.foo` と artifactId `acme` を使用してバージョン1.0-SNAPSHOTで Quarkus にエクスポートするには、次のコマンドを実行します。

[source, bash]
----
camel export <files> --runtime=quarkus --gav=com.foo:acme:1.0-SNAPSHOT --directory=./myproject
----

---

`camel export --runtime=spring-boot` コマンドは、現在のCamel JBangファイルを、Mavenベースの `Spring-boot` プロジェクトにエクスポートします。

例えば、Maven の groupId `com.foo` と artifactId `acme` を使用してバージョン1.0-SNAPSHOTで Spring-boot にエクスポートするには、次のコマンドを実行します。

[source, bash]
----
camel export <files> --runtime=spring-boot --gav=com.foo:acme:1.0-SNAPSHOT --directory=./myproject
----

== 4. 参考リンク 

* link:https://www.jbang.dev/[JBang,window="_blank"]
* link:https://camel.apache.org/manual/camel-jbang.html[Camel JBang,window="_blank"]