kind: Template
apiVersion: v1
metadata:
  name: kafdrop-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: kafdrop
      namespace: ${{PJ_NAME}}
      labels:
        app: kafdrop
      annotations:
        #app.openshift.io/connects-to: kafdrop
        app.openshift.io/vcs-uri: 'https://github.com/obsidiandynamics/kafdrop'
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        name: kafdrop
      template:
        metadata:
          name: kafdrop
          labels:
            name: kafdrop
        spec:
          containers:
            - name: kafdrop
              env:
                - name: KAFKA_BROKERCONNECT
                  value: "kafka-cluster-kafka-bootstrap.${{PJ_NAME}}.svc:9092"
              imagePullPolicy: IfNotPresent
              image: obsidiandynamics/kafdrop
              ports:
                - containerPort: 9000
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /actuator/health
                  port: 9000
                  scheme: HTTP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /actuator/health
                  port: 9000
                  scheme: HTTP
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: kafdrop
      labels:
        app: kafdrop
    spec:
      ports:
        - name: 9000-tcp
          port: 9000
          protocol: TCP
          targetPort: 9000
      selector:
        deploymentconfig: kafdrop
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: kafdrop
      name: kafdrop
    spec:
      port:
        targetPort: 9000-tcp
      to:
        kind: Service
        name: kafdrop
        weight: 100
parameters:
  - name: PJ_NAME
    displayName: project name
    description: project name
    value: "user1-dev"
    required: true