apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: debezium.public.products
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824