apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-12-15T00:01:05Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: c29bf20d-f8fa-4028-91bf-fd80fa34a397
  resourceVersion: "1679"
  uid: 4ed65d18-4d51-4a13-b7b3-2a90f7365cc0
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: camel-users # secret名
    mappingMethod: claim # アイデンティティーとユーザーオブジェクト間にマッピングが確立される方法
    name: camel-workshop # 任意のプロバイダー名
    type: HTPasswd
