kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: debezium-cone-template
objects:
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaConnect
    metadata:
      name: debezium-kafka-connect-cluster
      annotations:
        strimzi.io/use-connector-resources: "true"
    spec:
      version: 3.3.1
      build:
        output:
          type: imagestream
          image: debezium-streams-connect:latest
        plugins:
          - name: debezium-connector-postgres
            artifacts:
              - type: zip
                url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/2.1.4.Final-redhat-00001/debezium-connector-postgres-2.1.4.Final-redhat-00001-plugin.zip
                #url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/1.9.7.Final-redhat-00003/debezium-connector-postgres-1.9.7.Final-redhat-00003-plugin.zip
      bootstrapServers: kafka-cluster-kafka-bootstrap.user1-dev.svc:9092
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: debezium-streams-connect