kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: debezium-cone-template
objects:
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaConnector
    metadata:
      labels:
        strimzi.io/cluster: debezium-kafka-connect-cluster
      name: debezium-connector-postgresql
      namespace: ${PJ_NAME}
    spec:
      class: io.debezium.connector.postgresql.PostgresConnector
      tasksMax: 1
      config:
        #Kafka, DB接続情報
        database.history.kafka.bootstrap.servers: "kafka-cluster-kafka-bootstrap.${PJ_NAME}.svc:9092"
        database.history.kafka.topic: schema-changes.products
        database.hostname: "postgresql.${PJ_NAME}.svc.cluster.local"
        database.port: 5432
        database.user: demo
        database.password: demo
        database.dbname: sampledb
        database.server.name: postgresql

        #table.include.list: public.products #指定したテーブルのみがキャプチャされる
        topic.prefix: debezium #KafkaTopic名の接頭辞

        # 権限設定関連
        plugin.name: pgoutput
        publication.name: debezium
        slot.name: debezium
        publication.autocreate.mode: all_tables
        
        key.converter: org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable: false
        value.converter: org.apache.kafka.connect.json.JsonConverter
        value.converter.schemas.enable: false
parameters:
  - name: PJ_NAME
    displayName: project name
    description: project name
    value: "user1-dev"
    required: true