apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: debezium-kafka-connect-cluster
  name: debezium-connector-postgresql
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    #Kafka, DB接続情報
    database.history.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap.user1-dev.svc:9092
    database.history.kafka.topic: schema-changes.products
    database.hostname: postgresql.user1-dev.svc.cluster.local
    database.port: 5432
    database.user: demo
    database.password: demo
    database.dbname: sampledb
    database.server.name: postgresql

    #table.include.list: public.products #指定したテーブルのみがキャプチャされる
    topic.prefix: debezium #KafkaTopic名の接頭辞

    # 権限設定関連
    plugin.name: pgoutput
    publication.name: debezium
    slot.name: debezium
    publication.autocreate.mode: all_tables
    
    # single message transformation (SMT) 
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.add.fields: op,table,lsn,source.ts_ms
    transforms.unwrap.add.headers: db
    transforms.unwrap.delete.handling.mode: rewrite