apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  labels:
    app: camel-k
  name: example
spec:
  flows:
    - from:
        parameters:
          period: '1000'
        steps:
          - set-body:
              constant: Hello from Camel K
          - to: 'log:info'
        uri: 'timer:yaml'