kind: Template
apiVersion: template.openshift.io/v1
objects: 
- kind: DevWorkspace
  apiVersion: workspace.devfile.io/v1alpha2
  metadata:
    name: camelk-ws
    namespace: ${NAMESPACE_PARAM}
  spec:
    routingClass: che
    started: true
    contributions:
      - name: ide
        uri: ${DEVSPACES_URL}/plugin-registry/v3/plugins/che-incubator/che-code/latest/devfile.yaml
    template:
      projects:
        - name: camelk-ws-devspaces
          git:
            remotes:
              origin: https://github.com/team-ohc-jp-place/camelk-ws-devspaces
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-f5ffca8
            #image: registry.redhat.io/devspaces/udi-rhel8@sha256:b0dfd9e15d878785bea5cb33a82a014abbd08c839917e72a8cd629c84bf47f1e
            memoryRequest: 2Gi
            memoryLimit: 6Gi
            cpuLimit: 2000m
            cpuRequest: 1000m
      commands:
        - id: install
          exec:
            component: tools
            commandLine: |
              curl -Ls https://sh.jbang.dev | bash -s - app setup && 
              /home/user/.jbang/bin/jbang trust add -o --fresh --quiet https://github.com/apache/camel/blob/HEAD/dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
      events:
        postStart:
          - install
parameters: 
- name: DEVSPACES_URL
  displayName: OpenShift DevSpaces URL
  description: DEVSPACES_URL
  required: true
- name: NAMESPACE_PARAM
  displayName: OpenShift DevSpaces Namespace
  description: OpenShift DevSpaces Namespace
  required: true