kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: use-privileged-scc
subjects:
 - kind: ServiceAccount
   name: sftp-serviceaccount
roleRef:
 kind: Role
 name: privileged-scc
 apiGroup: rbac.authorization.k8s.io
