apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
        - name: sftp
          image: atmoz/sftp
          ports:
            - containerPort: 22
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
              - SYS_CHROOT
            runAsGroup: 0
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: sftp-pv
              mountPath: /home/user/upload
            - name: volume-sfq78
              mountPath: /etc/sftp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
      serviceAccount: sftp-serviceaccount
      serviceAccountName: sftp-serviceaccount
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: sftp-etc-sftp
          name: volume-sfq78
        - name: sftp-pv
          persistentVolumeClaim:
            claimName: sftp-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-service
spec:
  selector:
    app: sftp
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
