loggingLevel=info
loggingColor=true
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.7.0
camel.jbang.springBootVersion=3.3.1
camel.jbang.quarkusVersion=3.12.0
camel.jbang.kameletsVersion=4.7.0
